version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/athenian
    ports:
      - 3000:3000
    image: app:react
    container_name: athenian_container
    command: npm start 